services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    container_name: belimang_db
    environment:
      POSTGRES_DB: belimang
      POSTGRES_USER: belimang
      POSTGRES_PASSWORD: belimang
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U belimang"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: belimang_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-belimang}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-belimang}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: belimang_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: public.ecr.aws/ubuntu/grafana:latest
    container_name: belimang_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    restart: unless-stopped

volumes:
  db_data:
  minio_data: