FROM public.ecr.aws/docker/library/postgres:18-bookworm

# Install PostGIS
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgis \
    postgresql-18-postgis-3 \
    postgresql-18-postgis-3-scripts && \
    rm -rf /var/lib/apt/lists/*

# Copy initialization script
COPY init-postgis.sql /docker-entrypoint-initdb.d/

EXPOSE 5432