apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/team-kopi-db:v3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: belimang
            - name: POSTGRES_PASSWORD
              value: belimang
            - name: POSTGRES_DB
              value: belimang
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: PG_SHARED_MEMORY
              value: "2GB"
          resources:
            requests:
               memory: "4Gi"    # Request 4 GiB
               cpu: "1000m"     # Request 1 core
            limits:
               memory: "8Gi"    # Limit 8 GiB
               cpu: "2000m"     # Limit 2 core
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30081